{{- if .Values.productApi.enabled }}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.productApi.name }}-network-policy
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-api
spec:
  podSelector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: product-api
  policyTypes:
    - Ingress
    - Egress
  ingress:

    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: gateway
      ports:
        - protocol: TCP
          port: {{ .Values.productApi.service.port }}

    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: ecommerce
      ports:
        - protocol: TCP
          port: {{ .Values.productApi.service.port }}
  egress:

    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql-product
      ports:
        - protocol: TCP
          port: 5432

    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: auth-api
      ports:
        - protocol: TCP
          port: {{ .Values.authApi.service.port }}

    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
{{- end }}
